### PR TITLE
Remove reference to dead Pivotal Tracker URL

### PR DESCRIPTION
**Pull request by hiremaga**
cheffiles.pivotallabs.com is no longer online

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.chef.io/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @hiremaga

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by hiremaga** [comment]
I signed the CLA in December, 2013.

**Comment by jtimberman** [comment]
Obvious fix really. 

However if you haven't re signed the cla again after we launched supermarket you need to do so. We weren't able to import all the old clas.

**Comment by hiremaga** [comment]
Ah, that makes sense. Thanks!

**Comment by jtimberman** [comment]
At least it's SUPER easy now, and integrated with GitHub, rather than the form we had in the past with the echosign or whatever :ice_cream:

**Comment by chef-supermarket** [comment]
Hi. Your friendly Curry bot here. Just letting you know that all commit authors have become authorized to contribute. I have added the "Signed CLA" label to this issue so it can easily be found in the future.

**Comment by hiremaga** [comment]
Much easier :)

**Pull request merged**
