### PR TITLE
Add support for upgrading and uninstalling

### PR DESCRIPTION
**Pull request by hartmantis**
This adds an :remove action and rudimentary support for upgrades of packages registered in pkgutil by allowing a version to be passed to the resource. Makes it a little closer in functionality to other package resources. Also adds Test Kitchen configs and a few Serverspec tests.

I'm pretty new to command line package installs on OS X, so any feedback is much appreciated. Thanks!

### CODE REVIEW

**Comment by jtimberman** [comment]
This needs a rebase. It's definitely a desired feature, per https://github.com/jtimberman/vagrant-cookbook/issues/22#issuecomment-118246393.

**Comment by jfbibeau** [comment]
+1 this would be awesome - I'm guessing this PR is stale now?

**Comment by scarz** [comment]
@jfbibeau, I am afraid that yes :( So, you can try to add this through some wrapper cookbook or fork your own version of "dmg" and make changes there...

**Comment by jfbibeau** [comment]
@scarz yeah figured as much. Did the change in a fork in the end.

**Comment by racktear** [comment]
Hello, 

Is there anything I can help with to merge this? We really miss the support of upgrading packages and have to revert to using plain archives to install software.

**Comment by atikhono** [comment]
We miss the feature, please merge it

**Comment by atikhono** [comment]
@tas50 Could you please have a look? It's very important for us.

**Comment by RoboticCheese** [comment]
Have never had the time to give this the rebasing and refactoring it needs to be merge-able. If someone else feels like taking up the cause, please feel free.

**Pull request closed without merging**
